[project]
name = "document-search-service"
version = "0.1.0"
description = "Simple document search service"
readme = "README.md"
authors = [
    { name = "Artemiy", email = "artem.pospelov2018@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "elasticsearch>=8.15,<9",
    "flask>=3.1.3",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
